### ISSUE TITLE
minimum node version error message

### ISSUE THREAD

**Issue by afknapping** [egoist/create-vue-app#11]
i had accidentally started it under node 5.x and received the following error. a minimum major version check would be nice :)

would love to send a pull request, but have no idea where to start...

``` bash
/usr/local/lib/node_modules/create-vue-app/bin/init.js:23
    const {overWrite} = yield inquirer.prompt([{
          ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/create-vue-app/bin/cva.js:23:1)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
```

**Comment by egoist** [comment]
We can just set `engines.node >= 6` in package.json

**Comment by egoist** [comment]
Should be good now, closing.
