### ISSUE TITLE
An unexpected error occurred: "Invalid Version: next"

### ISSUE THREAD

**Issue by shyrz** [egoist/create-vue-app#4]
![image](https://cloud.githubusercontent.com/assets/5728981/23949501/6df279c6-09c2-11e7-9329-8280c8fbc7e6.png)
What happend... 😂

**Comment by shyrz** [comment]
Then I `cd my-app && yarn dev`

```bash
Failed to parse "/path/to/my-app/vbuild.config.js" as JSON, JS, or YAML.
```

😂

**Comment by egoist** [comment]
The first error might be related to network, what's in `yarn-error.log`?

The second error is fixed in `v0.2.3`

**Comment by shyrz** [comment]
```
Trace: 
  TypeError: Invalid Version: next
      at new SemVer (/Users/Phantr4x/.nvm/versions/node/v7.6.0/lib/node_modules/yarn/node_modules/semver/semver.js:293:11)
      at Range.test (/Users/Phantr4x/.nvm/versions/node/v7.6.0/lib/node_modules/yarn/node_modules/semver/semver.js:1036:15)
      at satisfies (/Users/Phantr4x/.nvm/versions/node/v7.6.0/lib/node_modules/yarn/node_modules/semver/semver.js:1085:16)
      at /Users/Phantr4x/.nvm/versions/node/v7.6.0/lib/node_modules/yarn/node_modules/semver/semver.js:1091:12
      at Array.filter (native)
      at Function.maxSatisfying (/Users/Phantr4x/.nvm/versions/node/v7.6.0/lib/node_modules/yarn/node_modules/semver/semver.js:1090:19)
      at PackageConstraintResolver.reduce (/Users/Phantr4x/.nvm/versions/node/v7.6.0/lib/node_modules/yarn/lib/package-constraint-resolver.js:23:37)
      at Config.resolveConstraints (/Users/Phantr4x/.nvm/versions/node/v7.6.0/lib/node_modules/yarn/lib/config.js:175:36)
      at /Users/Phantr4x/.nvm/versions/node/v7.6.0/lib/node_modules/yarn/lib/resolvers/registries/npm-resolver.js:73:38
      at Generator.next (<anonymous>)
```
Here it is

**Comment by shyrz** [comment]
It looks like got some trouble in `node` version?

**Comment by egoist** [comment]
it should be good money now, you can reopen this if the latest version does not work.
