### ISSUE TITLE
Syntax error when creating new app 

### ISSUE THREAD

**Issue by maxadorable** [egoist/create-vue-app#5]
I run this command
`ag_systems:~/workspace $ create-vue-app my-app`
I got this error
```
/home/ubuntu/workspace/node_modules/create-vue-app/bin/init.js:23
    const {overWrite} = yield inquirer.prompt([{
          ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/ubuntu/workspace/node_modules/create-vue-app/bin/cva.js:23:1)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10) ```

**Comment by egoist** [comment]
please use node 6 and above

**Comment by egoist** [comment]
it should be good now. so closing this.
